// This will be generated by Prisma after running migrations
// For now, we'll use a type that matches the schema
export type PrismaMovieListModel = {
    id: string;
    userId: string;
    name: string;
    isDefault: boolean;
    createdAt: Date;
    updatedAt: Date;
};

export default PrismaMovieListModel;

