// This will be generated by Prisma after running migrations
// For now, we'll use a type that matches the schema
export type PrismaMovieListItemModel = {
    id: string;
    movieListId: string;
    movieId: number;
    title: string;
    posterPath: string | null;
    releaseDate: string | null;
    overview: string | null;
    createdAt: Date;
    updatedAt: Date;
};

export default PrismaMovieListItemModel;

